routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\PenjelasanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    if (auth()->check()) {
        $user = auth()->user();

        if ($user->role === 'admin') {
            return redirect('/admin/dashboard');
        } elseif ($user->role === 'user') {
            if ($user->language_id === null) {
                return redirect('/select-language');
            } else {
                return redirect('/kelas');
            }
        }
    }
    return view('pages/welcome');
})->name('home');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', [AuthController::class, 'register'])->name('register');
    Route::post('/register', [AuthController::class, 'registerPost'])->name('register');
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'loginPost'])->name('login');
    Route::get('/verify/{token}', [AuthController::class, 'verify'])->name('verify');
    Route::get('/forgot-password', [AuthController::class, 'forgot']);
    Route::post('/forgot-password', [AuthController::class, 'forgot_password']);
    Route::get('/reset/{token}', [AuthController::class, 'reset']);
    Route::post('/reset/{token}', [AuthController::class, 'post_reset']);
    Route::get('/contact', [ReportController::class, 'report'])->name('report');
    Route::post('/submit-report', [ReportController::class, 'submitReport'])->name('submit-report');
});

Route::group(['middleware' => 'auth'], function () {
    Route::delete('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/select-language', [CourseController::class, 'selectLanguage'])->name('select.language');
    Route::post('/save-language', [CourseController::class, 'saveLanguage'])->name('save.language');
    Route::get('/kelas', [CourseController::class, 'index'])->name('course.index');
    Route::get('/kelas/{id}/level', [LevelController::class, 'showLevels'])->name('materi.levels');
    Route::get('/kelas/{materiId}/{levelId}/pages/', [PenjelasanController::class, 'penjelasan'])->name('level.pages');
    Route::get('/kelas/{materiId}/{levelId}/quiz/', [QuizController::class, 'quiz'])->name('quiz.pages');
    Route::get('/setting/akun', [UserController::class, 'editProfile'])->name('user.editProfile');
    Route::put('/setting/update/{id}', [UserController::class, 'updateProfile'])->name('user.updateProfile');
    Route::get('/setting/reset', [AuthController::class, 'password_reset'])->name('reset_password');
    Route::post('/setting/reset', [AuthController::class, 'pw_post_reset']);
    Route::get('/setting/bahasa', [UserController::class, 'showLanguageForm'])->name('language.form');
    Route::put('/setting/language/update', [UserController::class, 'updateLanguage'])->name('language.update');
    Route::get('/transaksi', [TransaksiController::class, 'pay'])->name('transaksi');
    Route::post('/transaksi', [TransaksiController::class, 'createTransaction'])->name('createTransaction');
    // Route::post('/transaksi/create', [TransaksiController::class, 'createTransaction']);
});

Route::middleware(['auth', 'checkUserRole:admin'])->group(function () {
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard']);
    // Route::get('/user-chart', [UserController::class, 'userRegistrationChart'])->name('user.chart');
    Route::resource('/admin/user', \App\Http\Controllers\UserController::class);
    Route::resource('/admin/menu', \App\Http\Controllers\MenuController::class);
    Route::resource('/admin/bahasa', \App\Http\Controllers\BahasaController::class);
    Route::resource('/admin/materi', \App\Http\Controllers\MateriController::class);
    Route::resource('admin/penilaian', \App\Http\Controllers\PenilaianController::class);
    Route::resource('/admin/penjelasan', \App\Http\Controllers\PenjelasanController::class);
    Route::resource('/admin/level', \App\Http\Controllers\LevelController::class);
    Route::resource('/admin/quiz', \App\Http\Controllers\QuizController::class);
    Route::resource('/admin/transaksi', \App\Http\Controllers\TransaksiController::class);
    // Route::get('/admin/dashboard/bahasa', [BahasaController::class, 'index'])->name('admin.bahasa.index');
});

app/Models/Level.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    use HasFactory;

    protected $fillable = [
        'nomor_level',
        'status',
        'parent_id'
    ];

    // menjadi child dari materi
    public function materi()
    {
        return $this->belongsTo(Materi::class, 'parent_id');
    }

    // menjadi parent dari penjelasan
    public function penjelasan()
    {
        return $this->hasMany(Penjelasan::class, 'parent_id');
    }
    public function quiz()
    {
        return $this->hasMany(Quiz::class, 'parent_id');
    }
}

app/Http/Controllers/LevelController.php
<?php

namespace App\Http\Controllers;

use App\Models\Level;
use App\Models\Materi;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;

class LevelController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $levels = Level::with('materi')->get();
        return view('admin.level.index', compact('levels'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $parents = Materi::with('level')->get();
        return view('admin.level.create', compact('parents'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $this->validate($request, [
            'nomor_level'     => 'required',
            'parent_id' =>  'required|exists:materis,id',
        ]);

        Level::create([
            'nomor_level'    => $request->nomor_level,
            'parent_id' => $request->input('parent_id'),
        ]);

        return redirect()->route('level.index')->with(['success' => 'Data Berhasil Disimpan!']);
    }

    /**
     * Display the specified resource.
     */
    public function show(Level $level)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Level $level)
    {
        $parents = Materi::with('level')->get();
        return view('admin.level.edit', compact('level', 'parents'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Level $level)
    {
        $this->validate($request, [
            'nomor_level'     => 'required',
            'parent_id' =>  'nullable|exists:materis,id',
        ]);

        $level->update([
            'nomor_level'    => $request->nomor_level,
            'parent_id' => $request->input('parent_id')
        ]);

        if ($request->input('parent_id')) {
            $activeParent = Level::find($request->input('parent_id'));
            $activeParent->update(['active' => true]);
        }

        return redirect()->route('level.index')->with(['success' => 'Data Berhasil Disimpan!']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Level $level)
    {
        // Simpan parent_id dan nomor_level
        $parent_id = $level->parent_id;
        $nomor_level = $level->nomor_level;

        // Hapus level
        $level->delete();

        // Perbarui nomor_level di level-level yang lebih besar
        $levelsToUpdate = Level::where('parent_id', $parent_id)
            ->where('nomor_level', '>', $nomor_level)
            ->get();

        foreach ($levelsToUpdate as $levelToUpdate) {
            $levelToUpdate->nomor_level -= 1;
            $levelToUpdate->save();
        }

        return redirect()->route('level.index')->with(['success' => 'Level berhasil dihapus.']);
    }

    public function showLevels($id)
    {
        $materi = Materi::findOrFail($id);
        $levels = Level::where('parent_id', $materi->id)->orderBy('nomor_level')->get();

        return view('pages.course.level', compact('levels', 'materi'));
    }
}

resources/views/admin/level/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>Create - Level - Golingua</title>
</head>

<body>
    @extends('admin.sidebar.index')

    @section('content')
        <form action="{{ route('level.store') }}" method="POST" enctype="multipart/form-data"
            class="bg-white p-5 shadow rounded-lg">
            @csrf
            <div class="flex gap-5">
                <div class="mb-6 w-full">
                    <label for="nomor_level" class="block mb-2 text-sm font-medium text-gray-900 ">NOMOR_LEVEL</label>
                    <input type="number" id="nomor_level"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="nomor_level" placeholder="Masukkan Nomor Level" required>
                </div>
                <div class="mb-6 w-full">
                    <label for="status" class="block mb-2 text-sm font-medium text-gray-900">STATUS</label>
                    <select id="status" name="status" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required>
                        <option value="terbuka">Terbuka</option>
                        <option value="terkunci">Terkunci</option>
                        <option value="selesai">Selesai</option>
                        <option value="belum selesai">Belum Selesai</option>
                    </select>
                </div>
                <select name="parent_id"
                    class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                    <option value="">Pilih Parent (Opsional)</option>
                    @foreach ($parents as $parent)
                        <option value="{{ $parent->id }}">{{ $parent->judul }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit"
                class="text-white bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">SIMPAN</button>
            <button type="reset"
                class="text-white bg-yellow-500 hover:bg-yellow-600 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">RESET</button>
        </form>
    @endsection

</body>

</html>

resources/views/admin/level/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>Edit - Level - Golingua</title>
</head>

<body>
    @extends('admin.sidebar.index')

    @section('content')
        <form action="{{ route('level.update', $level->id) }}" method="POST" enctype="multipart/form-data"
            class="bg-white p-5 shadow rounded-lg">
            @csrf
            @method('PUT')
            <div class="flex gap-5">
                <div class="mb-6 w-full">
                    <label for="nomor_level" class="block mb-2 text-sm font-medium text-gray-900 ">NOMOR_LEVEL</label>
                    <input type="number" id="nomor_level"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="nomor_level" value="{{ old('nomor_level', $level->nomor_level) }}" placeholder="Masukkan Nomor Level" required>
                </div>
                <div class="mb-6 w-full">
                    <label for="status" class="block mb-2 text-sm font-medium text-gray-900">STATUS</label>
                    <select id="status" name="status" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required>
                        <option value="terbuka" {{ old('status') === 'terbuka' ? 'selected' : '' }}>Terbuka</option>
                        <option value="terkunci" {{ old('status') === 'terkunci' ? 'selected' : '' }}>Terkunci</option>
                        <option value="selesai" {{ old('status') === 'selesai' ? 'selected' : '' }}>Selesai</option>
                        <option value="belum selesai" {{ old('status') === 'belum selesai' ? 'selected' : '' }}>Belum Selesai</option>
                    </select>
                </div>
                <select name="parent_id" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                    <option value="">Pilih Parent (Opsional)</option>
                    @foreach ($parents as $parent)
                        <option value="{{ $parent->id }}" {{ old('parent_id', $level->parent_id) == $parent->id ? 'selected' : '' }}>
                            {{ $parent->judul }}
                        </option>
                    @endforeach
                </select>
            </div>
            <button type="submit"
                class="text-white bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">SIMPAN</button>
            <button type="reset"
                class="text-white bg-yellow-500 hover:bg-yellow-600 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">RESET</button>
        </form>
    @endsection

</body>

</html>

resources/views/admin/level/index.blade.php
<!DOCTYPE html>
<html lang="en" class="antialiased">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>Level - GoLingua</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100;300;500;700;900&display=swap"
        rel="stylesheet">

    <meta name="description" content="">
    <meta name="keywords" content="">

    <!--Regular Datatables CSS-->
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
    <!--Responsive Extension Datatables CSS-->
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">

    <style>
        .font-league {
            font-family: 'League Spartan', sans-serif;
        }

        /*Form fields*/
        .dataTables_wrapper select,
        .dataTables_wrapper .dataTables_filter input {
            color: #4a5568;
            /*text-gray-700*/
            padding-left: 1rem;
            /*pl-4*/
            padding-right: 1rem;
            /*pl-4*/
            padding-top: .5rem;
            /*pl-2*/
            padding-bottom: .5rem;
            /*pl-2*/
            line-height: 1.25;
            /*leading-tight*/
            border-width: 2px;
            /*border-2*/
            border-radius: .25rem;
            border-color: #edf2f7;
            /*border-gray-200*/
            background-color: #edf2f7;
            /*bg-gray-200*/
        }

        /*Row Hover*/
        table.dataTable.hover tbody tr:hover,
        table.dataTable.display tbody tr:hover {
            background-color: #ebf4ff;
            /*bg-indigo-100*/
        }

        /*Pagination Buttons*/
        .dataTables_wrapper .dataTables_paginate .paginate_button {
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Pagination Buttons - Current selected */
        .dataTables_wrapper .dataTables_paginate .paginate_button.current {
            color: #fff !important;
            /*text-white*/
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
            /*shadow*/
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            background: #667eea !important;
            /*bg-indigo-500*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Pagination Buttons - Hover */
        .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
            color: #fff !important;
            /*text-white*/
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
            /*shadow*/
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            background: #667eea !important;
            /*bg-indigo-500*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Add padding to bottom border */
        table.dataTable.no-footer {
            border-bottom: 1px solid #e2e8f0;
            /*border-b-1 border-gray-300*/
            margin-top: 0.75em;
            margin-bottom: 0.75em;
        }

        /*Change colour of responsive icon*/
        table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before,
        table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
            background-color: #667eea !important;
            /*bg-indigo-500*/
        }
    </style>



</head>

<body class="bg-gray-100 text-gray-900 tracking-wider leading-normal">
    @extends('admin.sidebar.index')

    @section('content')
        <!--Container-->
        <div class="container w-full  mx-auto px-2 ">

            <div class="flex justify-between px-2 py-8">
                <h1 class="flex items-center font-sans font-bold break-normal text-indigo-500 text-xl md:text-2xl">
                    Data Level
                </h1>
                <a href="{{ route('level.create') }}" class="bg-indigo-500 px-4 py-2 rounded-md text-white">create</a>
            </div>


            <!--Card-->
            <div id='recipients' class="p-8 mt-6 lg:mt-0 rounded shadow bg-white">
                <table id="example" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                    <thead>
                        <tr>
                            <th data-priority="1">ID</th>
                            <th data-priority="2">Level</th>
                            <th data-priority="3" class="text-center">Parent</th>
                            <th data-priority="4"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($levels as $level)
                            <tr class="text-center">
                                <td>
                                    {{ $level->id }}
                                </td>
                                <td>
                                    {{ $level->nomor_level }}
                                </td>
                                <td>{{ $level->materi->judul }}</td>
                                <td class="flex justify-center items-center gap-2">
                                    <a href="{{ route('level.edit', ['level' => $level->id]) }}"
                                        class="bg-yellow-500 px-5 py-2 rounded-md text-white">Edit</a>
                                    <form action="{{ route('level.destroy', ['level' => $level->id]) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="bg-red-500 px-4 py-2 rounded-md text-white">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
        <!--/container-->

        <!-- jQuery -->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

        <!--Datatables -->
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
        <script>
            $(document).ready(function() {
                var table = $('#example').DataTable({
                    responsive: true,
                    lengthMenu: [5, 10, 25, 50], // Set the available options for entries per page
                    pageLength: 5 // Set the default number of rows to display per page
                });

                // Adjust and recalculate responsiveness
                table.columns.adjust().responsive.recalc();
            });
        </script>
    @endsection

</body>

</html>