routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\PenjelasanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    if (auth()->check()) {
        $user = auth()->user();

        if ($user->role === 'admin') {
            return redirect('/admin/dashboard');
        } elseif ($user->role === 'user') {
            if ($user->language_id === null) {
                return redirect('/select-language');
            } else {
                return redirect('/kelas');
            }
        }
    }
    return view('pages/welcome');
})->name('home');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', [AuthController::class, 'register'])->name('register');
    Route::post('/register', [AuthController::class, 'registerPost'])->name('register');
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'loginPost'])->name('login');
    Route::get('/verify/{token}', [AuthController::class, 'verify'])->name('verify');
    Route::get('/forgot-password', [AuthController::class, 'forgot']);
    Route::post('/forgot-password', [AuthController::class, 'forgot_password']);
    Route::get('/reset/{token}', [AuthController::class, 'reset']);
    Route::post('/reset/{token}', [AuthController::class, 'post_reset']);
    Route::get('/contact', [ReportController::class, 'report'])->name('report');
    Route::post('/submit-report', [ReportController::class, 'submitReport'])->name('submit-report');
});

Route::group(['middleware' => 'auth'], function () {
    Route::delete('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/select-language', [CourseController::class, 'selectLanguage'])->name('select.language');
    Route::post('/save-language', [CourseController::class, 'saveLanguage'])->name('save.language');
    Route::get('/kelas', [CourseController::class, 'index'])->name('course.index');
    Route::get('/kelas/{id}/level', [LevelController::class, 'showLevels'])->name('materi.levels');
    Route::get('/kelas/{materiId}/{levelId}/pages/', [PenjelasanController::class, 'penjelasan'])->name('level.pages');
    Route::get('/kelas/{materiId}/{levelId}/quiz/', [QuizController::class, 'quiz'])->name('quiz.pages');
    Route::get('/setting/akun', [UserController::class, 'editProfile'])->name('user.editProfile');
    Route::put('/setting/update/{id}', [UserController::class, 'updateProfile'])->name('user.updateProfile');
    Route::get('/setting/reset', [AuthController::class, 'password_reset'])->name('reset_password');
    Route::post('/setting/reset', [AuthController::class, 'pw_post_reset']);
    Route::get('/setting/bahasa', [UserController::class, 'showLanguageForm'])->name('language.form');
    Route::put('/setting/language/update', [UserController::class, 'updateLanguage'])->name('language.update');
    Route::get('/transaksi', [TransaksiController::class, 'pay'])->name('transaksi');
    Route::post('/transaksi', [TransaksiController::class, 'createTransaction'])->name('createTransaction');
    // Route::post('/transaksi/create', [TransaksiController::class, 'createTransaction']);
});

Route::middleware(['auth', 'checkUserRole:admin'])->group(function () {
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard']);
    // Route::get('/user-chart', [UserController::class, 'userRegistrationChart'])->name('user.chart');
    Route::resource('/admin/user', \App\Http\Controllers\UserController::class);
    Route::resource('/admin/menu', \App\Http\Controllers\MenuController::class);
    Route::resource('/admin/bahasa', \App\Http\Controllers\BahasaController::class);
    Route::resource('/admin/materi', \App\Http\Controllers\MateriController::class);
    Route::resource('admin/penilaian', \App\Http\Controllers\PenilaianController::class);
    Route::resource('/admin/penjelasan', \App\Http\Controllers\PenjelasanController::class);
    Route::resource('/admin/level', \App\Http\Controllers\LevelController::class);
    Route::resource('/admin/quiz', \App\Http\Controllers\QuizController::class);
    Route::resource('/admin/transaksi', \App\Http\Controllers\TransaksiController::class);
    // Route::get('/admin/dashboard/bahasa', [BahasaController::class, 'index'])->name('admin.bahasa.index');
});

app/Models/Penjelasan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Penjelasan extends Model
{
    use HasFactory;

    protected $fillable = [
        'judul',
        'isi',
        'contoh',
        'parent_id',
        'image'
    ];

    public function level()
    {
        return $this->belongsTo(Level::class, 'parent_id');
    }
}

app/Http/Controllers/PenjelasanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Quiz;
use App\Models\Level;
use App\Models\Penjelasan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PenjelasanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $penjelasans = Penjelasan::with('level')->paginate(5);
        return view('admin.penjelasan.index', compact('penjelasans'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $parents = Level::with('penjelasan')->get();
        return view('admin.penjelasan.create', compact('parents'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul'     => 'required',
            'isi'       => 'nullable',
            'contoh'    => 'nullable',
            'image'     => 'nullable|image|mimes:jpeg,jpg,png|max:2048',
            'parent_id' => 'nullable|exists:materis,id',
        ]);

        $image = $request->file('image');

        // Check if image is provided
        if ($image) {
            $image->storeAs('public/penjelasans', $image->hashName());
        }

        Penjelasan::create([
            'judul'      => $request->judul,
            'isi'        => $request->isi,
            'contoh'     => $request->contoh,
            'image'      => $image ? $image->hashName() : null,
            'parent_id'  => $request->input('parent_id'),
        ]);

        if ($request->input('parent_id')) {
            $activeParent = Penjelasan::find($request->input('parent_id'));
            $activeParent->update(['active' => true]);
        }

        return redirect()->route('penjelasan.index')->with(['success' => 'Data Berhasil Disimpan!']);
    }


    /**
     * Display the specified resource.
     */
    public function show(Penjelasan $penjelasan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Penjelasan $penjelasan)
    {
        $parents = Level::with('penjelasan')->get();
        return view('admin.penjelasan.edit', compact('penjelasan', 'parents'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Penjelasan $penjelasan)
    {
        $this->validate($request, [
            'judul'     => 'required',
            'isi'     => 'nullable',
            'contoh'     => 'nullable',
            'image'      => 'nullable|image|mimes:jpeg,jpg,png|max:2048',
            'parent_id' =>  'nullable',
        ]);

        $existingImage = $penjelasan->image;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $image->storeAs('public/penjelasans', $image->hashName());

            //hapus gambar lama
            if ($existingImage) {
                Storage::delete('public/penjelasans/' . $existingImage);
            }

            $penjelasan->update([
                'judul'    => $request->judul,
                'isi'    => $request->isi,
                'contoh'    => $request->contoh,
                'image'     => $image->hashName(),
                'parent_id' => $request->input('parent_id'),
            ]);
        } else {
            $penjelasan->update([
                'judul'    => $request->judul,
                'isi'    => $request->isi,
                'contoh'    => $request->contoh,
                'image'     => $existingImage,
                'parent_id' => $request->input('parent_id')
            ]);
        }

        return redirect()->route('penjelasan.index')->with(['success' => 'Data Berhasil Disimpan!']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Penjelasan $penjelasan)
    {
        Storage::delete('public/penjelasans/' . $penjelasan->image);
        $penjelasan->delete();
        return redirect()->route('penjelasan.index')->with(['success' => 'Data Berhasil di Delete']);
    }

    public function penjelasan($materiId, $levelId, $page = 1)
    {
        $penjelasans = Penjelasan::where('parent_id', $levelId)->with('level')->simplePaginate(1);

        return view('pages.course.pages', compact('penjelasans', 'materiId', 'levelId'));
    }
}

resources/views/admin/penjelasan/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>Create - Penjelasan - Golingua</title>
</head>

<body>
    @extends('admin.sidebar.index')

    @section('content')
        <form action="{{ route('penjelasan.store') }}" method="POST" enctype="multipart/form-data"
            class="bg-white p-5 shadow rounded-lg">
            @csrf
            <div class="flex gap-5">
                <div class="mb-6 w-full">
                    <label for="judul" class="block mb-2 text-sm font-medium text-gray-900 ">JUDUL</label>
                    <input type="text" id="judul"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="judul" placeholder="Masukkan Judul" required>
                </div>
                <div class="mb-6 w-full">
                    <label for="isi" class="block mb-2 text-sm font-medium text-gray-900 ">ISI</label>
                    <textarea id="isi"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="isi" placeholder="Masukkan Isi"></textarea>
                </div>
                <div class="mb-6 w-full">
                    <label for="contoh" class="block mb-2 text-sm font-medium text-gray-900">CONTOH</label>
                    <textarea id="contoh"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="contoh" placeholder="Masukkan Contoh" wrap="off"></textarea>
                </div>                
                <div class="mb-6 w-full">
                    <label for="image" class="block mb-2 text-sm font-medium text-gray-900">IMAGE</label>
                    <input
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 cursor-pointer"
                        name="image" id="image" type="file">
                </div>

                <select name="parent_id"
                    class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                    <option value="">Pilih Parent (Opsional)</option>
                    @foreach ($parents as $parent)
                        <option value="{{ $parent->id }}">
                            {{ $parent->nomor_level }} {{ $parent->materi->judul }}
                        </option>
                    @endforeach
                </select>
            </div>
            <button type="submit"
                class="text-white bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">SIMPAN</button>
            <button type="reset"
                class="text-white bg-yellow-500 hover:bg-yellow-600 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">RESET</button>
        </form>
    @endsection

</body>

</html>

resources/views/admin/penjelasan/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>Edit - Penjelasan - Golingua</title>
</head>

<body>
    @extends('admin.sidebar.index')

    @section('content')
        <form action="{{ route('penjelasan.update', $penjelasan->id) }}" method="POST" enctype="multipart/form-data"
            class="bg-white p-5 shadow rounded-lg">
            @csrf
            @method('PUT')
            <div class="flex gap-5">
                <div class="mb-6 w-full">
                    <label for="judul" class="block mb-2 text-sm font-medium text-gray-900 ">JUDUL</label>
                    <input type="text" id="judul"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="judul" value="{{ old('judul', $penjelasan->judul) }}" placeholder="Masukkan Judul" required>
                </div>
                <div class="mb-6 w-full">
                    <label for="isi" class="block mb-2 text-sm font-medium text-gray-900 ">ISI</label>
                    <input type="text" id="isi"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="isi" value="{{ old('isi', $penjelasan->isi) }}" placeholder="Masukkan Isi">
                </div>
                <div class="mb-6 w-full">
                    <label for="contoh" class="block mb-2 text-sm font-medium text-gray-900 ">CONTOH</label>
                    <input type="text" id="contoh"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                        name="contoh" value="{{ old('contoh', $penjelasan->contoh) }}" placeholder="Masukkan Contoh">
                </div>

                <div class="mb-6 w-full">
                    <label for="image" class="block mb-2 text-sm font-medium text-gray-900">IMAGE</label>
                    <input
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 cursor-pointer"
                        name="image" aria-describedby="user_avatar_help" id="user_avatar" type="file">
                </div>

                <select name="parent_id" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                    <option value="">Pilih Parent (Opsional)</option>
                    @foreach ($parents as $parent)
                        <option value="{{ $parent->id }}" {{ old('parent_id', $penjelasan->parent_id) == $parent->id ? 'selected' : '' }}>
                                {{ $parent->nomor_level }} {{ $parent->materi->judul }}
                        </option>
                    @endforeach
                </select>
            </div>
            <button type="submit"
                class="text-white bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">SIMPAN</button>
            <button type="reset"
                class="text-white bg-yellow-500 hover:bg-yellow-600 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">RESET</button>
        </form>
    @endsection

</body>

</html>

resources/views/admin/penjelasan/index.blade.php
<!DOCTYPE html>
<html lang="en" class="antialiased">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>Penjelasan - GoLingua</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100;300;500;700;900&display=swap"
        rel="stylesheet">

    <meta name="description" content="">
    <meta name="keywords" content="">

    <!--Regular Datatables CSS-->
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
    <!--Responsive Extension Datatables CSS-->
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">

    <style>
        .font-league {
            font-family: 'League Spartan', sans-serif;
        }

        /*Form fields*/
        .dataTables_wrapper select,
        .dataTables_wrapper .dataTables_filter input {
            color: #4a5568;
            /*text-gray-700*/
            padding-left: 1rem;
            /*pl-4*/
            padding-right: 1rem;
            /*pl-4*/
            padding-top: .5rem;
            /*pl-2*/
            padding-bottom: .5rem;
            /*pl-2*/
            line-height: 1.25;
            /*leading-tight*/
            border-width: 2px;
            /*border-2*/
            border-radius: .25rem;
            border-color: #edf2f7;
            /*border-gray-200*/
            background-color: #edf2f7;
            /*bg-gray-200*/
        }

        /*Row Hover*/
        table.dataTable.hover tbody tr:hover,
        table.dataTable.display tbody tr:hover {
            background-color: #ebf4ff;
            /*bg-indigo-100*/
        }

        /*Pagination Buttons*/
        .dataTables_wrapper .dataTables_paginate .paginate_button {
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Pagination Buttons - Current selected */
        .dataTables_wrapper .dataTables_paginate .paginate_button.current {
            color: #fff !important;
            /*text-white*/
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
            /*shadow*/
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            background: #667eea !important;
            /*bg-indigo-500*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Pagination Buttons - Hover */
        .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
            color: #fff !important;
            /*text-white*/
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
            /*shadow*/
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            background: #667eea !important;
            /*bg-indigo-500*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Add padding to bottom border */
        table.dataTable.no-footer {
            border-bottom: 1px solid #e2e8f0;
            /*border-b-1 border-gray-300*/
            margin-top: 0.75em;
            margin-bottom: 0.75em;
        }

        /*Change colour of responsive icon*/
        table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before,
        table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
            background-color: #667eea !important;
            /*bg-indigo-500*/
        }
    </style>



</head>

<body class="bg-gray-100 text-gray-900 tracking-wider leading-normal">
    @extends('admin.sidebar.index')

    @section('content')
        <!--Container-->
        <div class="container w-full  mx-auto px-2 ">

            <div class="flex justify-between px-2 py-8">
                <h1 class="flex items-center font-sans font-bold break-normal text-indigo-500 text-xl md:text-2xl">
                    Data Penjelasan
                </h1>
                <a href="{{ route('penjelasan.create') }}" class="bg-indigo-500 px-4 py-2 rounded-md text-white">create</a>
            </div>


            <!--Card-->
            <div id='recipients' class="p-8 mt-6 lg:mt-0 rounded shadow bg-white">
                <table id="example" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                    <thead>
                        <tr>
                            <th data-priority="1">ID</th>
                            <th data-priority="2">Judul</th>
                            <th data-priority="3">Isi</th>
                            <th data-priority="4">Contoh</th>
                            <th data-priority="5">Gambar</th>
                            <th data-priority="6">Level</th>
                            <th data-priority="7"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($penjelasans as $penjelasan)
                            <tr>
                                <td class="text-center">
                                    {{ $penjelasan->id }}
                                </td>
                                <td>
                                    {{ $penjelasan->judul }}
                                </td>
                                <td>
                                    {{ $penjelasan->isi }}
                                </td>
                                <td>
                                    <p>{!! nl2br(e($penjelasan->contoh)) !!}</p>
                                </td>
                                <td class="text-center">
                                    @if ($penjelasan->image)
                                        <img src="{{ asset('/storage/penjelasans/' . $penjelasan->image) }}" style="width: 50px" class="mx-auto rounded">
                                    @else
                                    @endif
                                </td>
                                <td class="text-center">{{ optional($penjelasan->level)->nomor_level }}</td>
                                <td class="flex justify-center items-center gap-2">
                                    <a href="{{ route('penjelasan.edit', ['penjelasan' => $penjelasan->id]) }}"
                                        class="bg-yellow-500 px-5 py-2 rounded-md text-white">Edit</a>
                                    <form action="{{ route('penjelasan.destroy', ['penjelasan' => $penjelasan->id]) }}"
                                        method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="bg-red-500 px-4 py-2 rounded-md text-white">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
        <!--/container-->

        <!-- jQuery -->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

        <!--Datatables -->
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
        <script>
            $(document).ready(function() {
                var table = $('#example').DataTable({
                    responsive: true,
                    lengthMenu: [5, 10, 25, 50], // Set the available options for entries per page
                    pageLength: 5 // Set the default number of rows to display per page
                });

                // Adjust and recalculate responsiveness
                table.columns.adjust().responsive.recalc();
            });
        </script>
    @endsection

</body>

</html>