routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\PenjelasanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', function () {
    if (auth()->check()) {
        $user = auth()->user();

        if ($user->role === 'admin') {
            return redirect('/admin/dashboard');
        } elseif ($user->role === 'user') {
            if ($user->language_id === null) {
                return redirect('/select-language');
            } else {
                return redirect('/kelas');
            }
        }
    }
    return view('pages/welcome');
})->name('home');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/register', [AuthController::class, 'register'])->name('register');
    Route::post('/register', [AuthController::class, 'registerPost'])->name('register');
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'loginPost'])->name('login');
    Route::get('/verify/{token}', [AuthController::class, 'verify'])->name('verify');
    Route::get('/forgot-password', [AuthController::class, 'forgot']);
    Route::post('/forgot-password', [AuthController::class, 'forgot_password']);
    Route::get('/reset/{token}', [AuthController::class, 'reset']);
    Route::post('/reset/{token}', [AuthController::class, 'post_reset']);
    Route::get('/contact', [ReportController::class, 'report'])->name('report');
    Route::post('/submit-report', [ReportController::class, 'submitReport'])->name('submit-report');
});

Route::group(['middleware' => 'auth'], function () {
    Route::delete('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/select-language', [CourseController::class, 'selectLanguage'])->name('select.language');
    Route::post('/save-language', [CourseController::class, 'saveLanguage'])->name('save.language');
    Route::get('/kelas', [CourseController::class, 'index'])->name('course.index');
    Route::get('/kelas/{id}/level', [LevelController::class, 'showLevels'])->name('materi.levels');
    Route::get('/kelas/{materiId}/{levelId}/pages/', [PenjelasanController::class, 'penjelasan'])->name('level.pages');
    Route::get('/kelas/{materiId}/{levelId}/quiz/', [QuizController::class, 'quiz'])->name('quiz.pages');
    Route::get('/setting/akun', [UserController::class, 'editProfile'])->name('user.editProfile');
    Route::put('/setting/update/{id}', [UserController::class, 'updateProfile'])->name('user.updateProfile');
    Route::get('/setting/reset', [AuthController::class, 'password_reset'])->name('reset_password');
    Route::post('/setting/reset', [AuthController::class, 'pw_post_reset']);
    Route::get('/setting/bahasa', [UserController::class, 'showLanguageForm'])->name('language.form');
    Route::put('/setting/language/update', [UserController::class, 'updateLanguage'])->name('language.update');
    Route::get('/transaksi', [TransaksiController::class, 'pay'])->name('transaksi');
    Route::post('/transaksi', [TransaksiController::class, 'createTransaction'])->name('createTransaction');
    // Route::post('/transaksi/create', [TransaksiController::class, 'createTransaction']);
});

Route::middleware(['auth', 'checkUserRole:admin'])->group(function () {
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard']);
    // Route::get('/user-chart', [UserController::class, 'userRegistrationChart'])->name('user.chart');
    Route::resource('/admin/user', \App\Http\Controllers\UserController::class);
    Route::resource('/admin/menu', \App\Http\Controllers\MenuController::class);
    Route::resource('/admin/bahasa', \App\Http\Controllers\BahasaController::class);
    Route::resource('/admin/materi', \App\Http\Controllers\MateriController::class);
    Route::resource('admin/penilaian', \App\Http\Controllers\PenilaianController::class);
    Route::resource('/admin/penjelasan', \App\Http\Controllers\PenjelasanController::class);
    Route::resource('/admin/level', \App\Http\Controllers\LevelController::class);
    Route::resource('/admin/quiz', \App\Http\Controllers\QuizController::class);
    Route::resource('/admin/transaksi', \App\Http\Controllers\TransaksiController::class);
    // Route::get('/admin/dashboard/bahasa', [BahasaController::class, 'index'])->name('admin.bahasa.index');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Attribute;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'profile_image',
        'language_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];


    public function penilaian()
    {
        return $this->hasMany(Penilaian::class, 'user_id');
    }

    static public function getSingle($id)
    {
        return self::find($id);
    }
    public function language()
    {
        return $this->belongsTo(Bahasa::class, 'language_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Bahasa;
use App\Models\Transaksi;
use App\Models\Subscription;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::latest()->get();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        $languages = Bahasa::pluck('bahasa', 'id');
        return view('admin.user.edit', compact('user', 'languages'));
    }


    public function update(Request $request, string $id)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                Rule::unique('users')->ignore($id), // Exclude the current user by ID
            ],
            'profile_image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048', // Maksimal 2MB
            'role' => 'required',
            'language_id' => 'required',
        ]);

        $validRoles = ['admin', 'user'];
        if (!in_array($request->role, $validRoles)) {
            return redirect()->back()->with('error', 'Peran yang dimasukkan tidak valid.');
        }

        // Temukan pengguna yang ingin diubah
        $user = User::find($id);

        // Update atribut pengguna jika diperlukan
        if ($user) {
            $user->name = $request->name;
            $user->email = $request->email;
            $user->role = $request->role;
            $user->language_id = $request->language_id;

            if ($request->hasFile('image')) {
                // Hapus gambar lama jika ada
                if ($user->profile_image) {
                    Storage::delete('public/profile_images/' . $user->profile_image);
                }

                // Upload gambar profil yang baru
                $profileImage = $request->file('image');
                $imageName = time() . '.' . 'jpg';
                $profileImage->storeAs('public/profile_images', $imageName);
                $user->profile_image = $imageName;
            }


            $user->save();

            // dd($request->all());
            return redirect()->route('user.index')->with(['success' => "Data Berhasil di Update!"]);
        } else {
            return redirect()->route('user.index')->with(['error' => "Pengguna tidak ditemukan."]);
        }
    }

    public function destroy($id)
    {
        $user = User::find($id);

        if ($user) {
            // Hapus gambar profil jika ada
            if ($user->profile_image) {
                Storage::delete('public/profile_images/' . $user->profile_image);
            }

            // Hapus pengguna dari database
            $user->delete();

            return redirect()->route('user.index')->with(['success' => "User berhasil dihapus"]);
        } else {
            return redirect()->route('user.index')->with(['error' => "User tidak ditemukan"]);
        }
    }


    /**
     * Show the form for editing the user's profile.
     */
    public function editProfile()
    {
        $user = auth()->user();
        return view('pages.akun.editProfile', compact('user'));
    }

    /**
     * Update the user's profile information.
     */
    public function updateProfile(Request $request, string $id)
    {
        $user = User::find($id);

        $request->validate([
            'name' => 'nullable|string|max:255',
            'email' => [
                'nullable',
                'string',
                'email',
                'max:255',
                Rule::unique('users')->ignore($user->id),
            ],
            'profile_image' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

        // Update only the fields that are provided in the request
        $user->fill($request->only(['name', 'email']));

        if ($request->hasFile('profile_image')) {
            $profileImage = $request->file('profile_image');
            $imageName = time() . '.' . $profileImage->extension();
            $profileImage->storeAs('public/profile_images', $imageName);
            $user->profile_image = $imageName;
        }

        $user->save();

        return redirect()->route('user.editProfile')->with(['success' => "Profile Updated successfully!"]);
    }

    public function showLanguageForm()
    {
        $user = Auth::user();
        $bahasas = Bahasa::all();
        return view('pages.setting.bahasa', compact('user', 'bahasas'));
    }

    public function updateLanguage(Request $request)
    {
        // Validasi formulir
        $request->validate([
            'language_id' => 'required|exists:bahasas,id',
        ]);

        // Perbarui kolom language_id untuk pengguna yang sedang masuk
        $user = Auth::user();
        $successfulTransaction = Transaksi::where('email', $user->email)->where('status', 'sukses')->first();

        if ($successfulTransaction) {
            return redirect('/transaksi')->with(['error' => 'Anda tidak dapat mengubah bahasa karena telah menyelesaikan transaksi.']);
        }

        // Update language_id
        $user->language_id = $request->input('language_id');
        $user->save();

        // Redirect or provide response as needed
        return redirect()->route('course.index')->with('success', 'Bahasa berhasil diperbarui');
    }
}

resources/views/admin/user/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>Create - User - Golingua</title>
</head>

<body>
    @extends('admin.sidebar.index')

    @section('content')
        <form action="{{ route('user.update', ['user' => $user->id]) }}" method="post" enctype="multipart/form-data"
            class="bg-white p-5 shadow rounded-lg">
            @csrf
            @method('PUT')
            <div class="flex gap-5">
                <div class="mb-6 w-full">
                    <label for="user" class="block mb-2 text-sm font-medium text-gray-900 ">NAME</label>
                    <input type="text" id="user"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 @error('name') is-invalid @enderror"
                        name="name" value="{{ old('name', $user->name) }}" placeholder="Masukkan Nama" required>

                    <!-- error message untuk name -->
                    @error('name')
                        <div class="mt-2">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-6 w-full">
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 ">EMAIL</label>
                    <input type="text" id="email"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 @error('email') is-invalid @enderror"
                        name="email" value="{{ old('email', $user->email) }}" placeholder="Masukkan Email" required>

                    <!-- error message untuk name -->
                    @error('email')
                        <div class="mt-2">
                            {{ $message }}
                        </div>
                    @enderror
                </div>

                <div class="mb-6 w-full">
                    <label for="profil_image" class="block mb-2 text-sm font-medium text-gray-900">PROFIL IMAGE</label>
                    <input type="file" id="profil_image" name="image"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 cursor-pointer @error('profil_image') is-invalid @enderror"
                        aria-describedby="user_avatar_help">


                    @error('profil_image')
                        <div class="mt-2 text-red-500">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
            </div>

            <div class="flex gap-5">
                <div class="mb-6 w-1/2">
                    <label for="role" class="block mb-2 text-sm font-medium text-gray-900 ">ROLE</label>
                    <select id="role" name="role"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                        <option value="admin" @if (old('role', $user->role) === 'admin') selected @endif>Admin</option>
                        <option value="user" @if (old('role', $user->role) === 'user') selected @endif>User</option>
                    </select>
                </div>

                <div class="mb-6 w-1/2">
                    <label for="language_id" class="block mb-2 text-sm font-medium text-gray-900">LANGUAGE</label>
                    <select name="language_id"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                        @foreach ($languages as $id => $bahasa)
                            <option value="{{ $id }}">{{ $bahasa }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <button type="submit"
                class="text-white bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">SIMPAN</button>
            <button type="reset"
                class="text-white bg-yellow-500 hover:bg-yellow-600 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">RESET</button>
        </form>
    @endsection

</body>

</html>

resources/views/admin/user/index.blade.php
{{-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>User - GoLingua</title>
</head>

<body>
    @extends('admin.sidebar.index')

    @section('content')
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 ">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                    <tr>
                        <th scope="col" class="px-6 py-3">ID</th>
                        <th scope="col" class="px-6 py-3">NAME</th>
                        <th scope="col" class="px-6 py-3">EMAIL</th>
                        <th scope="col" class="px-6 py-3 text-center">IMAGE</th>
                        <th scope="col" class="px-6 py-3">ROLE</th>
                        <th scope="col" class="px-6 py-3">LANGUAGE ID</th>
                        <th scope="col" class="px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($users as $user)
                        <tr class="bg-white border-b ">
                            <th scope="row" class="px-6 py-4 font-medium  whitespace-nowrap">
                                {{ $user->id }}
                            </th>
                            <td class="px-6 py-4">
                                {{ $user->name }}
                            </td>
                            <td class="px-6 py-4">
                                {{ $user->email }}
                            </td>
                            <td class="px-6 py-4 flex justify-center items-center">
                                @if ($user->profile_image)
                                    <img src="{{ asset('storage/profile_images/' . $user->profile_image) }}"
                                        alt="User Profile Image" class="rounded object-cover"
                                        style="width: 50px; height: 40px">
                                @else
                                @endif
                            </td>
                            <td class="px-6 py-4">
                                {{ $user->role }}
                            </td>
                            <td class="px-6 py-4">
                                {{ $user->language_id }}
                            </td>
                            <td class="px-6 py-4 text-right">
                                <div>
                                    <a href="{{ route('user.edit', ['user' => $user->id]) }}"
                                        class="font-medium text-blue-600 hover:underline">Edit</a>
                                    <form action="{{ route('user.destroy', ['user' => $user->id]) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="font-medium text-red-600 hover:underline">Hapus</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <div>
                            Empty Data.
                        </div>
                    @endforelse
                </tbody>
            </table>
            <div class="border-none">
                {{ $users->links() }}
            </div>
        </div>
    @endsection

</body>

</html> --}}



<!DOCTYPE html>
<html lang="en" class="antialiased">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <title>User - GoLingua</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100;300;500;700;900&display=swap"
        rel="stylesheet">

    <meta name="description" content="">
    <meta name="keywords" content="">

    <!--Regular Datatables CSS-->
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
    <!--Responsive Extension Datatables CSS-->
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">

    <style>
        .font-league {
            font-family: 'League Spartan', sans-serif;
        }

        /*Form fields*/
        .dataTables_wrapper select,
        .dataTables_wrapper .dataTables_filter input {
            color: #4a5568;
            /*text-gray-700*/
            padding-left: 1rem;
            /*pl-4*/
            padding-right: 1rem;
            /*pl-4*/
            padding-top: .5rem;
            /*pl-2*/
            padding-bottom: .5rem;
            /*pl-2*/
            line-height: 1.25;
            /*leading-tight*/
            border-width: 2px;
            /*border-2*/
            border-radius: .25rem;
            border-color: #edf2f7;
            /*border-gray-200*/
            background-color: #edf2f7;
            /*bg-gray-200*/
        }

        /*Row Hover*/
        table.dataTable.hover tbody tr:hover,
        table.dataTable.display tbody tr:hover {
            background-color: #ebf4ff;
            /*bg-indigo-100*/
        }

        /*Pagination Buttons*/
        .dataTables_wrapper .dataTables_paginate .paginate_button {
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Pagination Buttons - Current selected */
        .dataTables_wrapper .dataTables_paginate .paginate_button.current {
            color: #fff !important;
            /*text-white*/
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
            /*shadow*/
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            background: #667eea !important;
            /*bg-indigo-500*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Pagination Buttons - Hover */
        .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
            color: #fff !important;
            /*text-white*/
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06);
            /*shadow*/
            font-weight: 700;
            /*font-bold*/
            border-radius: .25rem;
            /*rounded*/
            background: #667eea !important;
            /*bg-indigo-500*/
            border: 1px solid transparent;
            /*border border-transparent*/
        }

        /*Add padding to bottom border */
        table.dataTable.no-footer {
            border-bottom: 1px solid #e2e8f0;
            /*border-b-1 border-gray-300*/
            margin-top: 0.75em;
            margin-bottom: 0.75em;
        }

        /*Change colour of responsive icon*/
        table.dataTable.dtr-inline.collapsed>tbody>tr>td:first-child:before,
        table.dataTable.dtr-inline.collapsed>tbody>tr>th:first-child:before {
            background-color: #667eea !important;
            /*bg-indigo-500*/
        }
    </style>



</head>

<body class="bg-gray-100 text-gray-900 tracking-wider leading-normal">
    @extends('admin.sidebar.index')

    @section('content')
        <!--Container-->
        <div class="container w-full  mx-auto px-2">

            <!--Title-->
            <h1 class="flex items-center font-sans font-bold break-normal text-indigo-500 px-2 py-8 text-xl md:text-2xl">
                Data User
            </h1>


            <!--Card-->
            <div id='recipients' class="p-8 mt-6 lg:mt-0 rounded shadow bg-white">
                <table id="example" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
                    <thead>
                        <tr>
                            <th data-priority="1">ID</th>
                            <th data-priority="2">Nama</th>
                            <th data-priority="3">Email</th>
                            <th data-priority="4">Foto</th>
                            <th data-priority="5">Role</th>
                            <th data-priority="6">Bahasa</th>
                            <th data-priority="7"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td class="text-center">
                                    {{ $user->id }}
                                </td>
                                <td>
                                    {{ $user->name }}
                                </td>
                                <td>
                                    {{ $user->email }}
                                </td>
                                <td class="text-center">
                                    @if ($user->profile_image)
                                        <img src="{{ asset('storage/profile_images/' . $user->profile_image) }}"
                                            alt="User Profile Image" class="rounded object-cover"
                                            style="width: 50px; height: 40px">
                                    @else
                                    @endif
                                </td>
                                <td class="text-center">{{ $user->role }}</td>
                                <td class="text-center">{{ $user->language_id }}</td>
                                <td class="flex justify-center items-center gap-2">
                                    <a href="{{ route('user.edit', ['user' => $user->id]) }}"
                                        class="bg-yellow-500 px-5 py-2 rounded-md text-white">Edit</a>
                                    <form action="{{ route('user.destroy', ['user' => $user->id]) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="bg-red-500 px-4 py-2 rounded-md text-white">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
        <!--/container-->

        <!-- jQuery -->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

        <!--Datatables -->
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
        <script>
            $(document).ready(function() {
                var table = $('#example').DataTable({
                    responsive: true,
                    lengthMenu: [5, 10, 25, 50], // Set the available options for entries per page
                    pageLength: 5 // Set the default number of rows to display per page
                });

                // Adjust and recalculate responsiveness
                table.columns.adjust().responsive.recalc();
            });
        </script>
    @endsection

</body>

</html>